"""Versioned contracts for whole-script content analysis.

The v1 contract stays provider-neutral. Ark persistence, transport and the
whole-script orchestration layer are exported separately for workbench use.
"""

from app.services.content_analysis.ark import (
    ArkAPIError,
    ArkClient,
    ark_client_from_config,
)
from app.services.content_analysis.ark_accounts import (
    ARK_DEFAULT_BASE_URL,
    save_ark_config,
    validate_ark_config,
)
from app.services.content_analysis.analysis import (
    CONTENT_ANALYSIS_PROMPT_VERSION,
    ArkConcurrencyLimiter,
    ContentAnalysisInputError,
    ContentAnalysisUnavailable,
    analyze_content,
    ark_response_format,
    build_ark_messages,
)

from app.services.content_analysis.contracts import (
    CONTENT_ANALYSIS_SCHEMA_VERSION,
    CONTENT_ANALYSIS_PROVIDER_SCHEMA_VERSION,
    ContentVisualContext,
    ContentAnalysisContractError,
    ContentAnalysisResult,
    MusicIntent,
    SubtitleUnit,
    VisualAnchor,
    VisualConcept,
    VisualPlanItem,
    content_analysis_json_schema,
    parse_content_analysis_payload,
    parse_music_intent_payload,
    parse_content_visual_context,
    parse_subtitle_units_payload,
    parse_visual_plan_payload,
    visual_context_sha256,
    validate_subtitle_units,
)
from app.services.content_analysis.taxonomy import (
    MUSIC_MATCHER_HARD_FILTERS_V1,
    MUSIC_MATCHER_VERSION,
    MUSIC_MATCHER_WEIGHTS_V1,
    ContentFormat,
    ContentTopic,
    MusicAvoidTrait,
    MusicMood,
    MusicScene,
    OpeningPreference,
    Pace,
    SpeechDensity,
    Valence,
    VocalPreference,
)

__all__ = [
    "CONTENT_ANALYSIS_SCHEMA_VERSION",
    "CONTENT_ANALYSIS_PROVIDER_SCHEMA_VERSION",
    "ARK_DEFAULT_BASE_URL",
    "CONTENT_ANALYSIS_PROMPT_VERSION",
    "ArkConcurrencyLimiter",
    "ContentAnalysisInputError",
    "ContentAnalysisUnavailable",
    "analyze_content",
    "ark_response_format",
    "build_ark_messages",
    "MUSIC_MATCHER_HARD_FILTERS_V1",
    "MUSIC_MATCHER_VERSION",
    "MUSIC_MATCHER_WEIGHTS_V1",
    "ContentAnalysisContractError",
    "ContentAnalysisResult",
    "ContentVisualContext",
    "ContentFormat",
    "ContentTopic",
    "MusicAvoidTrait",
    "MusicIntent",
    "MusicMood",
    "MusicScene",
    "OpeningPreference",
    "Pace",
    "SpeechDensity",
    "SubtitleUnit",
    "VisualAnchor",
    "VisualConcept",
    "VisualPlanItem",
    "Valence",
    "VocalPreference",
    "ArkAPIError",
    "ArkClient",
    "ark_client_from_config",
    "content_analysis_json_schema",
    "parse_content_analysis_payload",
    "parse_music_intent_payload",
    "parse_content_visual_context",
    "parse_subtitle_units_payload",
    "parse_visual_plan_payload",
    "save_ark_config",
    "validate_ark_config",
    "validate_subtitle_units",
    "visual_context_sha256",
]
